name: $(date:yyyyMMdd)$(rev:.r)

trigger:
  branches:
    include:
    - main
  batch: True

pr:
  branches:
    include:
      - main
  paths:
    include:
      - code\TemplateStudioForWPF
      - code\src\ProjectTemplates\WPF
      - code\test\TemplateStudioForWPF.Tests

resources:
  repositories:
  - repository: self
    type: git
    ref: refs/heads/main

variables:
- name: NUGET.PLUGIN.HANDSHAKE.TIMEOUT.IN.SECONDS
  value: 20
- name: NUGET.PLUGIN.REQUEST.TIMEOUT.IN.SECONDS
  value: 20

jobs:
- template: templates/ci-build.yml
  parameters:
    Moniker: WPF
    BuildConfiguration: ReleaseWPF
    BuildPlatform: Any CPU

- template: templates/ci-test.yml
  parameters:
    Moniker: WPF
    BuildConfiguration: DebugWPF
    BuildPlatform: Any CPU