name: $(date:yyyyMMdd)$(rev:.r)

trigger:
  branches:
    include:
    - main
  batch: True

pr:
- main

resources:
  repositories:
  - repository: self
    type: git
    ref: refs/heads/main

variables:
- name: NUGET.PLUGIN.HANDSHAKE.TIMEOUT.IN.SECONDS
  value: 20
- name: NUGET.PLUGIN.REQUEST.TIMEOUT.IN.SECONDS
  value: 20

jobs:
- job:
  displayName: Build
  timeoutInMinutes: 240

  strategy:
    matrix:
      WinUICs:
        BuildConfiguration: ReleaseWinUICs
        BuildPlatform: Any CPU
      WinUICpp:
        BuildConfiguration: ReleaseWinUICpp
        BuildPlatform: Any CPU
      WPF:
        BuildConfiguration: ReleaseWPF
        BuildPlatform: Any CPU
      UWP:
        BuildConfiguration: ReleaseUWP
        BuildPlatform: Any CPU

  pool:
    vmImage: windows-2022

  steps:
  - checkout: self
    clean: true
    submodules: recursive

  - task: NuGetToolInstaller@1
    displayName: Use NuGet
    inputs:
      checkLatest: true

  - task: NuGetCommand@2
    displayName: NuGet restore
    inputs:
      solution: code/TemplateStudio.sln

  - task: VSBuild@1
    displayName: Build
    inputs:
      solution: code/TemplateStudio.sln
      vsVersion: 17.0
      msbuildArgs: /p:DeployExtension=false
      configuration: $(BuildConfiguration)
      platform: $(BuildPlatform)
      clean: true

  - task: CopyFiles@1
    displayName: Copy Artifacts
    condition: and(succeededOrFailed(), in(variables['Build.Reason'], 'IndividualCI', 'BatchedCI'))
    inputs:
      SourceFolder: $(Build.SourcesDirectory)
      Contents: '**\bin\$(BuildConfiguration)\**'
      TargetFolder: $(Build.ArtifactStagingDirectory)
    
  - task: PublishBuildArtifacts@1
    displayName: Publish Artifacts
    condition: and(succeededOrFailed(), in(variables['Build.Reason'], 'IndividualCI', 'BatchedCI'))
    inputs:
      PathtoPublish: $(Build.ArtifactStagingDirectory)
      TargetPath: '\\my\share\$(Build.DefinitionName)\$(Build.BuildNumber)'

- job:
  displayName: Test
  timeoutInMinutes: 240

  strategy:
    matrix:
      WinUICs:
        Moniker: WinUICs
        BuildConfiguration: DebugWinUICs
        BuildPlatform: Any CPU
      WinUICpp:
        Moniker: WinUICpp
        BuildConfiguration: DebugWinUICpp
        BuildPlatform: Any CPU
      WPF:
        Moniker: WPF
        BuildConfiguration: DebugWPF
        BuildPlatform: Any CPU
      # Reenable as part of #4441
      #UWP:
      #  Moniker: UWP
      #  BuildConfiguration: DebugUWP
      #  BuildPlatform: Any CPU

  pool:
    vmImage: windows-2022

  steps:
  - checkout: self
    clean: true
    submodules: recursive

  - task: NuGetToolInstaller@1
    displayName: Use NuGet
    inputs:
      checkLatest: true

  - task: NuGetCommand@2
    displayName: NuGet restore
    inputs:
      solution: code/TemplateStudio.sln

  - task: VSBuild@1
    displayName: Build
    inputs:
      solution: code/TemplateStudio.$(Moniker).slnf
      vsVersion: 17.0
      configuration: $(BuildConfiguration)
      platform: $(BuildPlatform)
      clean: true

  - task: BatchScript@1
    displayName: Set Agent Drive and Clean Test Folder
    inputs:
      filename: _build/SetAgentDriveAndCleanTestFolder.bat
      modifyEnvironment: true

  - task: PowerShell@1
    displayName: Test
    inputs:
      scriptName: _build/ParallelTestExecution.ps1
      arguments: -testRunner $(UserProfile)/.nuget/packages/xunit.runner.console/2.4.1/tools/net47/xunit.console.exe -testLibrary $(Build.SourcesDirectory)/code/test/TemplateStudioFor$(Moniker).Tests/bin/Debug/TemplateStudioFor$(Moniker).Tests.dll -traits 'Group=Minimum$(Moniker)' -outputDir $(Build.SourcesDirectory)

  - task: PublishTestResults@2
    displayName: Publish Test Results
    condition: succeededOrFailed()
    inputs:
      testRunner: XUnit
      testResultsFiles: '**/TEST-*.xml'

- job:
  displayName: Test Shared
  timeoutInMinutes: 240

  strategy:
    matrix:
      UI:
        Moniker: UI
        FrameworkDirectory: .
        BuildConfiguration: DebugALL
        BuildPlatform: Any CPU
      Core:
        Moniker: Core
        FrameworkDirectory: net472
        BuildConfiguration: DebugALL
        BuildPlatform: Any CPU

  pool:
    vmImage: windows-2022

  steps:
  - checkout: self
    clean: true
    submodules: recursive

  - task: NuGetToolInstaller@1
    displayName: Use NuGet
    inputs:
      checkLatest: true

  - task: NuGetCommand@2
    displayName: NuGet restore
    inputs:
      solution: code/TemplateStudio.sln

  - task: VSBuild@1
    displayName: Build
    inputs:
      solution: code/TemplateStudio.SharedTests.CI.slnf
      vsVersion: 17.0
      configuration: $(BuildConfiguration)
      platform: $(BuildPlatform)
      clean: true

  - task: BatchScript@1
    displayName: Set Agent Drive and Clean Test Folder
    inputs:
      filename: _build/SetAgentDriveAndCleanTestFolder.bat
      modifyEnvironment: true

  - task: PowerShell@1
    displayName: Test
    inputs:
      scriptName: _build/ParallelTestExecution.ps1
      arguments: -testRunner $(UserProfile)/.nuget/packages/xunit.runner.console/2.4.1/tools/net47/xunit.console.exe -testLibrary $(Build.SourcesDirectory)/code/test/SharedFunctionality.$(Moniker).Tests/bin/Debug/$(FrameworkDirectory)/SharedFunctionality.$(Moniker).Tests.dll -traits 'Group=Minimum' -outputDir $(Build.SourcesDirectory)

  - task: PublishTestResults@2
    displayName: Publish Test Results
    condition: succeededOrFailed()
    inputs:
      testRunner: XUnit
      testResultsFiles: '**/TEST-*.xml'