name: $(date:yyyyMMdd)$(rev:.r)

trigger: none

pr: none

schedules:
- cron: 0 5 * * *
  branches:
    include:
    - main

resources:
  repositories:
  - repository: self
    type: git
    ref: refs/heads/main

jobs:
- job:
  displayName: Test

  strategy:
    matrix:
      WinUICs:
        Moniker: WinUICs
        BuildConfiguration: DebugWinUICs
        BuildPlatform: Any CPU
      WinUICpp:
        Moniker: WinUICpp
        BuildConfiguration: DebugWinUICpp
        BuildPlatform: Any CPU
      WPF:
        Moniker: WPF
        BuildConfiguration: DebugWPF
        BuildPlatform: Any CPU
      UWP:
        Moniker: UWP
        BuildConfiguration: DebugUWP
        BuildPlatform: Any CPU

  pool:
    vmImage: windows-2022

  steps:
  - checkout: self
    clean: true
    submodules: recursive

  - task: NuGetToolInstaller@1
    displayName: Use NuGet
    inputs:
      checkLatest: true

  - task: NuGetCommand@2
    displayName: NuGet restore
    inputs:
      solution: code/TemplateStudio.sln

  - task: VSBuild@1
    displayName: Build
    inputs:
      solution: code/TemplateStudio.$(Moniker).slnf
      vsVersion: 17.0
      configuration: $(BuildConfiguration)
      platform: $(BuildPlatform)
      clean: true

  - task: BatchScript@1
    displayName: Set Agent Drive and Clean Test Folder
    inputs:
      filename: _build/SetAgentDriveAndCleanTestFolder.bat
      modifyEnvironment: true

  - task: PowerShell@1
    displayName: Test
    inputs:
      scriptName: _build/ParallelTestExecution.ps1
      arguments: -testRunner $(UserProfile)/.nuget/packages/xunit.runner.console/2.4.1/tools/net47/xunit.console.exe -testLibrary $(Build.SourcesDirectory)/code/test/TemplateStudioFor$(Moniker).Tests/bin/Debug/TemplateStudioFor$(Moniker).Tests.dll -traits 'Group=Build$(Moniker)' -outputDir $(Build.SourcesDirectory)

  - task: PublishTestResults@2
    displayName: Publish Test Results
    condition: succeededOrFailed()
    inputs:
      testRunner: XUnit
      testResultsFiles: '**/TEST-*.xml'

- job:
  displayName: Test Shared

  strategy:
    matrix:
      Core:
        Moniker: Core
        FrameworkDirectory: net472
        BuildConfiguration: DebugALL
        BuildPlatform: Any CPU
      UI:
        Moniker: UI
        FrameworkDirectory: .
        BuildConfiguration: DebugALL
        BuildPlatform: Any CPU

  pool:
    vmImage: windows-2022

  steps:
  - checkout: self
    clean: true
    submodules: recursive

  - task: NuGetToolInstaller@1
    displayName: Use NuGet
    inputs:
      checkLatest: true

  - task: NuGetCommand@2
    displayName: NuGet restore
    inputs:
      solution: code/TemplateStudio.sln

  - task: VSBuild@1
    displayName: Build
    inputs:
      solution: code/TemplateStudio.sln
      vsVersion: 17.0
      configuration: $(BuildConfiguration)
      platform: $(BuildPlatform)
      clean: true

  - task: BatchScript@1
    displayName: Set Agent Drive and Clean Test Folder
    inputs:
      filename: _build/SetAgentDriveAndCleanTestFolder.bat
      modifyEnvironment: true

  - task: PowerShell@1
    displayName: Test
    inputs:
      scriptName: _build/ParallelTestExecution.ps1
      arguments: -testRunner $(UserProfile)/.nuget/packages/xunit.runner.console/2.4.1/tools/net47/xunit.console.exe -testLibrary $(Build.SourcesDirectory)/code/test/SharedFunctionality.$(Moniker).Tests/bin/Debug/$(FrameworkDirectory)/SharedFunctionality.$(Moniker).Tests.dll -traits 'Group=Build' -outputDir $(Build.SourcesDirectory)

  - task: PublishTestResults@2
    displayName: Publish Test Results
    condition: succeededOrFailed()
    inputs:
      testRunner: XUnit
      testResultsFiles: '**/TEST-*.xml'